# Beispielkonfiguration für den Labeler
# Weise Labels basierend auf Dateipfaden zu

"feature":
  - changed-files:
      - any-glob-to-any-file:
          - src/features/**
"core":
  - changed-files:
      - any-glob-to-any-file:
          - src/core/**
"config":
  - changed-files:
      - any-glob-to-any-file:
          - src/config/**
"i18n":
  - changed-files:
      - any-glob-to-any-file:
          - src/i18n/**
"docs":
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
"build":
  - changed-files:
      - any-glob-to-any-file:
          - tools/**
          - .github/workflows/**
